version: "2.4"
services:
  iris-xgb-server:
    container_name: iris-xgb-server
    image: nvcr.io/nvidia/tritonserver:22.04-py3
    command: tritonserver --model-repository=/model_repository --model-control-mode=explicit --load-model iris_xgboost --trace-file=/tmp/trace.json --trace-rate=100 --trace-level=MAX
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    volumes:
      - ./model_repository:/model_repository
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8002/metrics"]
        interval: 30s
        timeout: 10s
        retries: 5
  iris-xgb-client:
    container_name: iris-xgb-client
    image: iris-app:latest
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
      - TRITON_SERVER=iris-xgb-server
    ports:
      - "8265:8265"
      - "6060:6060"
    links:
      - iris-xgb-server:iris-xgb-server
    ipc: "host"
    stdin_open: true # NOTE: temporary solution to make the process blocking
    tty: true        # NOTE: temporary solution to make the process blocking